"""Add session_id to Quote

Revision ID: 211645f2c3ac
Revises: 
Create Date: 2025-06-16 08:42:44.143481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211645f2c3ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
